//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDPersona.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int ID { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El nombre no puede quedar vacío.")]
        public string Nombre { get; set; }
        [Display(Name = "Apellidos")]
        [Required(ErrorMessage = "Los apellidos no pueden quedar vacíos.")]
        public string Apellido { get; set; }
        [Display(Name = "Edad")]
        [Required(ErrorMessage = "La edad no puede quedar vacía")]
        public string Edad { get; set; }
        [Display(Name = "Dirección")]
        [Required(ErrorMessage = "La dirección no puede quedar vacía")]
        public string Direccion { get; set; }
        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "El teléfono no puede quedar vacío")]
        public string Telefono { get; set; }
    }
}
